# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "Minty"
  port = 8910
  apiUrl = "/api"
  includeEnvironmentVariables = ['MORALIS_SERVER_URL','MORALIS_API_ID'
  ,'MORALIS_MASTER_KEY','ASSET_STORE_BASE_URL','ASSET_STORE_BASE_PATH'
  ,'SUPABASE_URL','SUPABASE_KEY','RAR_PRODUCTION','RAR_STAGING','CLOUDINARY_URL'
  ,'FUNCTIONS_PATH','PINATA_API_KEY','PINATA_API_SECRET','RINKEBY_TOKEN_CONTRACT','MAINNET_TOKEN_CONTRACT'
  ,'DATABASE_URL','TEST_DATABASE_URL'] # any ENV vars that should be available to the web side, see https://redwoodjs.com/docs/environment-variables#web
[api]
  port = 8911
[browser]
  open = true
